logging:
  level:
    com:
      rua:
        OpenAIClient: INFO # Set to Debug to log feign requests/responses
  org:
    springframework:
      web: DEBUG # Displays error logs of, for example, bad request

management:
  endpoints:
    web:
      exposure:
        include: beans # Expose actuator beans

spring:
  datasource:
    username: rua
    url: jdbc:sqlserver://;serverName=gpt4fun.database.windows.net;databaseName=gpt4fun
    password: Myh.1059331302
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none # Disable Hibernate automatic schema creation
  sql:
    init:
      mode: always # Initialize the database, do not use deprecated spring.datasource.initialization-mode
      schema-locations: classpath:sql/schema.sql
  web:
    resources:
      static-locations:
        static-locations[0]: "file:src/main/resources/static/"
        static-locations[1]: "classpath:/static/"